version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - '${MQTT_PORT}:${MQTT_PORT}'
      - '${MQTT_WS_PORT}:${MQTT_WS_PORT}'
    volumes:
      - ./volumes/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./volumes/mqtt/data:/mosquitto/data
      - ./volumes/mqtt/log:/mosquitto/log
    restart: always
    network_mode: bridge
